def words
  [
    ["football", "22 humans but no hands"],
    ["cinema", "Grab some popcorn"],
    ["carbonated", "Shakey bubbles"],
    ["dinosaur", "Cold-blooded history"],
    ["headphones", "Music to your ears"],
    ["cactus", "Never thirsty"],
    ["charger", "Electron transporter"],
    ["narwhal", "One tuskateer"],
    ["kettle", "Click for heat"],
    ["photograph", "Immortal paper"],
    ["extension", "Longing for more"],
    ["nectarine", "Juicy fruit"],
    ["bluetooth", "Poor oral hygiene"],
    ["telephone", "Far reaching words"],
    ["microwave", "You spin me right round"],
    ["gorilla", "You after a laborious shave"],
    ["bungalow", "Ground zero"],
    ["recliner", "Relax!"],
    ["painting", "An oily scene"],
    ["fireworks", "Very high BOOM"],
    ["wreath", "A decorative circle"],
    ["casino", "Man Vs House"],
    ["accident", "Don't blame me!"],
    ["addition", "More not less"],
    ["networks", "Fishing for interconnected people"],
    ["committed", "Focus your insanity"],
    ["kangaroo", "Australian kick boxer"],
    ["airplane", "Skim wood in the clouds"],
    ["universal", "One thing to fit them all"],
    ["synthetic", "Person-made"],
    ["compound", "An interested mixture"],
  ]
end
